default: cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/MortgageView.java
	javac cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/MortgageView.java
	
run: cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/MortgageView.java
	java cpsc2150.mortgages.MortgageApp

clean:
	rm -f cpsc2150/mortgages/*.class
