default: cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java
	javac cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java
run: cpsc2150/connectX/Connect4Game.class
	java cpsc2150/connectX.Connect4Game
clean:
	rm -f cpsc2150/connectX/*.class
