default: cpsc2150/interfaces/MultiSetApp.java cpsc2150/interfaces/DoubleSetApp.java cpsc2150/interfaces/ArraySet.java cpsc2150/interfaces/ListSet.java cpsc2150/interfaces/ISet.java cpsc2150/interfaces/SetAbs.java
	javac -Xlint:unchecked cpsc2150/interfaces/MultiSetApp.java cpsc2150/interfaces/DoubleSetApp.java cpsc2150/interfaces/ArraySet.java cpsc2150/interfaces/ListSet.java cpsc2150/interfaces/ISet.java cpsc2150/interfaces/SetAbs.java
runInt: cpsc2150/interfaces/MultiSetApp.class
	java cpsc2150/interfaces.MultiSetApp
runDouble: cpsc2150/interfaces/DoubleSetApp.class
	java cpsc2150/interfaces.DoubleSetApp
clean:
	rm -f cpsc2150/interfaces/*.class
