default: cpsc2150/matrixFun/MatrixApp.java cpsc2150/matrixFun/Matrix.java
	javac cpsc2150/matrixFun/MatrixApp.java javac cpsc2150/matrixFun/Matrix.java
run: cpsc2150/matrixFun/MatrixApp.class
	java cpsc2150/matrixFun.MatrixApp
clean:
	rm -f *.class
